---
- name: Install Apache HTTP Server (httpd)
  hosts: Production
  become: yes

  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: present

  - name: Start and enable httpd service
    service:
      name: httpd
      state: started
      enabled: yes
