---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum: 
      update_cache: yes

  - name: install httpd package
    yum:
      name: httpd

  - name: install firewalld package
    yum:
      name: firewalld 
