---
- name: Uninstall httpd
  hosts: Production 
  become: true
  tasks:
    - name: Stop httpd service
      service:
        name: httpd
        state: stopped
    - name: Remove httpd package
      yum:
        name: httpd
        state: absent
